<?php include('header.php');  ?>

<body>
    <div id="wrapper">
	
	<?php include('top_nav.php');  ?>
        <!-- /. NAV TOP  -->
		<?php include('cal.php');  ?>
	<?php include('side_nav.php');  ?>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-head-line">Payment Details</h1>
                        

                    </div>
                </div>
                <!-- /. ROW  -->

                <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
               <div class="panel panel-info">
                        
                        <div class="panel-body">
						
						<?php include('val.php'); ?>
						<?php
						
						include 'razorpay-php/Razorpay.php';
 //$apiKey = "rzp_test_YxfkUbFXwfG4Vc";
 use Razorpay\Api\Api;


$keyId = 'rzp_test_9RzFxChAkkAoJg';
$secretKey = 'sM3qTwUpvA99SzYYwSWfnO3C';
$api = new Api($keyId, $secretKey);

						$pet_details_id=$_REQUEST['pet_details_id'];
						$pet_request_id=$_REQUEST['pet_request_id'];
						$pet_name=$_REQUEST['pet_name'];
						$pet_price=$_REQUEST['pet_price'];
						$firstname='Sandeep';
						$contno='8431138839';
						$email_id='sandeephegde7348@gmail.com';

$paise=$pet_price*100;

$order= $api->order->create(array(
'receipt'=>rand(1000,9999).'ORD',
'amount'=>$paise,
'payment_capture'=>1,
'currency'=>'INR',)
);

						?>
<form name="form1" id="formID" method="post" action="user_payment_insert.php">
<input type="hidden" name="pet_request_id" value="<?php echo $pet_request_id;?>">
<input type="hidden" name="pet_details_id" value="<?php echo $pet_details_id;?>">
  <table width="519" height="402" border="0" align="center">
  
    <tr>
      <td width="246" height="70"><div align="center"><span class="style2">Pet Name </span></div></td>
      <td width="305"><input name="pet_name" type="text" value="<?php echo $pet_name; ?>" readonly="" id="pet_name" class="form-control validate[required]"></td>
    </tr>
    <tr>
      <td height="70"><div align="center"><span class="style2">Pet Price </span></div></td>
      <td><input name="pet_price" id="pet_price" tyep="text" value="<?php echo $pet_price; ?>" readonly="" type="text"  class="form-control validate[required]"></td>
    </tr>
    
  </table>
  <script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $keyId; ?>" // Enter the Test API Key ID generated from Dashboard ? Settings ? API Keys
    data-amount="<?php echo $order->amount; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ?299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php echo $order->id ?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="AMAZING PET"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://th.bing.com/th/id/R.897f1e71df2aab31247429e848b2f715?rik=Zv%2bt3G6Z8sxk2A&riu=http%3a%2f%2ficons.iconarchive.com%2ficons%2fgoogle%2fnoto-emoji-animals-nature%2f1024%2f22215-dog-icon.png&ehk=2GWo9pIImhfr8FKA0QXz%2fwFzx8RNOcssO6XdpVAKw7Y%3d&risl=&pid=ImgRaw&r=0"
    data-prefill.name="<?php echo $firstname;  ?>"
	data-prefill.contact="<?php echo $contno;  ?>"
    data-prefill.email="<?php echo $email_id ?>"
    data-theme.color="#4380B8"
></script>

</form>
</div>
                        </div>
                            </div>


        </div>
                <!--/.ROW-->

            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->
	
<?php include('footer.php');  ?>